### ISSUE TITLE
[conjure-java-local] Replace external imports with the base type

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-conjure#1370]
## What happened?

When running conjure-java-locally to generate client bindings for a remotely-published conjure file, the local generation fails if the remote conjure file has external imports that are unavailable locally.

There have been a few categories of external imports that I've seen so far:
1. external import of a Java class generated from the current conjure project (an antipattern; I fixed that instance)
2. external import of a Java class included in the remote conjure project's published jar.  For many users of conjure-java-local, a desired outcome is to sever the gradle dependency on the remote project's published jar, so they want to avoid re-introducing it.
3. external import of a Java class part of the JDK (e.g. java.time classes). These are probably fine to keep in the locally-generated client

## What did you want to happen?
I'd like local generation of the conjure client to succeed even if the remote conjure file uses external imports.

To fix, @carterkozak suggests that the generation of the local client should fall back to the base type.  For most of the imports I'm observing, I think that would be `String`

**Comment by carterkozak** [comment]
See https://github.com/palantir/conjure-java/pull/2213
