### ISSUE TITLE
5.0.0 hangs builds

### ISSUE THREAD

**Issue by VVKot** [palantir/gradle-conjure#693]
## What happened?

`compile` tasks on CI fail after upgrade from `4.27.2` to `5.0.0`.  `./gradlew --parallel --stacktrace --rerun-tasks classes testClasses` consistently reproduced the problem on internal repo, please reach out for a link.

## What did you want to happen?

Builds are not hanging.

**Comment by fawind** [comment]
Fixed through workaround in https://github.com/palantir/conjure-java/pull/1211.

**Comment by netcazean** [comment]
#678
