### ISSUE TITLE
Copy IR into target projects as resource

### ISSUE THREAD

**Issue by esword** [palantir/gradle-conjure#760]
## What happened?
I am working on something that does build-time analysis in java projects that consume conjure APIs to determine what endpoints are called.  I need access to the IR for this to work.  I have a hacky way to figure out the name of the IR artifact for a given conjure-jar dependency and go download it (e.g. if a project has 'my-company:my-api-dialogue' as a dependency, I can figure out that the IR artifact is 'my-company:my-api' and search repostories for where to download it).  It would be much cleaner though if the IR was in the jar itself as a resource file.

## What did you want to happen?
Put the conjure.json file in the jar at the root level, preferably with a standard name like just "conjure.json".  Or, if there will ever be multiple conjure.json files in a jar, could just keep them with the name of the generated file directly as it comes from the compileIr task.

## Proposed Solutions
I have experimented with a couple of ways to do this:

1. Add the output directory of the compileIR task directly as a resource directory of the derived projects.  Can also make tweaks to the ConjureJavaLocalCodegenPlugin and ConjureLocalPlugin to pass in their source IRs as well in a similar way.  This takes the least amount of code, but is not canonical gradle because the derived project is then reaching outside of it's project directory for some of it's resources.

2. Add a new copyIrToXXX task to the derived java projects (objects, retrofit, jersey, etc) that copies the IR into src/generated/resources.  This is the most obvious way to do things and doesn't require much code, but it is more than the first option and also doesn't easily extend to generic generators (which I have)

3. Add an optional to property to ConjureGeneratorTask for irOutputDirectory.  If set, the generator task will copy over the source IRs to the directory.  This is the least intrusive and makes it easy for anything else that configures a generator (including the local stuff and generic generators) to copy the IR.

Thoughts?

**Comment by carterkozak** [comment]
Do we need the entire IR with object definitions, or just the mapping from data that uniquely identifies an endpoint (`GET /foo`)  to the minimum product dependency version for that endpoint? Could we add the minimal mapping the same way we handle overall product dependency info?
https://github.com/palantir/gradle-conjure/blob/26d43e19fba43f19868cc425136cade8e1b12656/gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaServiceDependencies.java#L35-L42
https://github.com/palantir/sls-packaging/blob/dfe72e21b3578f14dbb7f7b5019e4fc5a05db5b1/gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/ConfigureProductDependenciesTask.java#L34-L80

**Comment by esword** [comment]
That mapping you talk about is in an extension written by a different (internal) project.  The gradle-conjure project has no knowledge of that data or format, nor does the sls-packaging project (which reads the configured ProductDependencies that are set into memory) know what to do with anything other than ProductDependencies.  Unless we're going to define standards up to the SLS level for this info, I think copying in the IR is more straightforward and most generalizable.

**Comment by carterkozak** [comment]
The jar manifest isn't the same as the sls manifest, it's just an implementation detail of our build tooling. I don't think there's anything wrong with speccing out the data structure we need into `gradle-recommended-product-dependencies`, in fact that seems like the best place for it to live. What do you think, @fawind?

**Comment by fawind** [comment]
I think I would also prefer using a more narrowed down representation that's specific to our use-case instead of storing the entire conjure def. That way the intend is clearer and we keep our api surface small.

However when producing the api jar, do we have all the information at hand to build this minimal mapping in gradle-conjure/sls-packaging?

**Comment by esword** [comment]
Yes, we met yesterday and I'm going to put up some proposed PRs for this information in the RecommendedDependencyPlugin in sls-packaging.
