### ISSUE TITLE
Published Conjure IR should include service dependency information

### ISSUE THREAD

**Issue by sfackler** [palantir/gradle-conjure#864]
There are two ways of consuming an external service's Conjure API:

1. You consume generated code published by the external service.
2. You consume Conjure IR published by the external service and generate code from it locally.

In case 1, we embed service dependency information in the generated library which can be picked up by build tooling for your service. However, that is not true in case 2. In particular, Rust services always use case 2 since we don't expect all services to be publishing Rust crates for their Conjure APIs. Local generation also has advantages in that you are able to configure the codegen how you like (WRT things like staged builders) instead of having to deal with whatever the external service decided.

Unfortunately, we currently publish the Conjure IR JSON directly. We could either add service dependency information to the Conjure IR spec itself, or make a breaking change to IR publishing and wrap it in a tarball, allowing us to stick the service dependency information next to it.

**Comment by iamdanfox** [comment]
@sfackler it's not enforced in the types, but I think if you look in the `extensions` block of most published Conjure IR, you'll find a `recommended-product-dependencies` thing (and also apparently a `apiMinVersion` and `endpointVersions` fields).

It was added back here (https://github.com/palantir/conjure/pull/532) for the exact use-case you're describing, of being able to still convey product dependencies to anyone who wanted to consume IR and generate clients locally.

**Comment by sfackler** [comment]
Oh, fantastic!
