### ISSUE TITLE
Support local code-gen for external IR files

### ISSUE THREAD

**Issue by k-simons** [palantir/gradle-conjure#92]
I would like to be able to generate local jars from an IR file that has been produced by another project. Currently in an unfortunate position of having a non-java repo publish an IR file to artifactory. I'd like to consume that IR file in a java repo and generate jars from it so I can build a client.

cc @ferozco

**Comment by bmoylan** [comment]
@iamdanfox any plans for this? We just hit it again on a different project and it requires a good amount of manual wiring to have gradle download and use an IR file.

It seems strange to me that the current best practice is to generate and publish a jar after we went through all the work of standardizing the IR.

**Comment by willdeuschle** [comment]
Is there a timeline on this? I'm also now hitting this issue and my two options seem to be 1) manually gen and publish a jar and then tell downstream consumers to go use that or 2) use a hack that fakes publishing then consuming those objects

**Comment by ferozco** [comment]
Sorry for the late response, but I think this has been addressed by #36
